# -*- coding: utf-8 -*-
"""Score .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-xQV_8iYwQYTYn9f4z-eOvu5N-RQXzU
"""

count_failing = 0

# 讀取一整行成績，並以空格分隔成字串列表
grade_strings = input().split()

# 迭代每一個成績字串
for grade_str in grade_strings:
    try:
        # 將字串轉換為整數
        grade = int(grade_str)
        # 判斷是否為不及格（假設不及格分數為 60 以下）
        if grade < 60:
            count_failing += 1
    except ValueError:
        print(f"警告：'{grade_str}' 不是一個有效的成績，已跳過。")

print(f"不及格的成績數量為：{count_failing}")

