# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cnYPv207bTd_ck4k6D8h6Fa_t05AeEf

### 計算不及格成績數量

這個程式會要求您輸入一串以空格分隔的成績。程式會將這些成績轉換為數字，檢查它們是否在 0 到 100 的範圍內，然後計算並印出不及格（分數小於 60）的成績數量。
"""

def count_failing_scores():
    score_input = input("請輸入一串成績，以空格分隔（例如：85 72 45 60 91）： ")
    scores_str = score_input.split()

    failing_count = 0
    valid_scores = []
    total_score = 0

    for score_s in scores_str:
        try:
            score = int(score_s)
            if 0 <= score <= 100:
                valid_scores.append(score)
                total_score += score
                if score < 60:
                    failing_count += 1
            else:
                print(f"警告：分數 {score} 不在 0 到 100 的有效範圍內，將忽略此分數。")
        except ValueError:
            print(f"警告：'{score_s}' 不是有效的數字，將忽略此輸入。")

    print(f"\n此串成績中不及格的數量為：{failing_count}")

    if valid_scores:
        average_score = total_score / len(valid_scores)
        print(f"此串有效成績的平均數為：{average_score:.2f}")
    else:
        print("沒有有效的成績可以計算平均數。")

# 執行函數
count_failing_scores()